// Automatically generated by Makefile. DO NOT EDIT!

#pragma once

#define BOOTLOADER_START_ADDRESS 0x7800
#define EEPROM_CONFIGURATION_START_BYTE 0x03F6

#define RESET_VECTOR 0x0000
#define RESET_VECTOR_ARGUMENT_ADDRESS 0x0002

static uint16_t jmp_instruction = 0x940c;
